lid_model:
  models_dir: "lid-models"

  lid_model_train_settings:
    epochs: 12
    batch_size: 64

lid_dataset:
  path: "/home/azureuser/datasets/spectrograms"
  train_dir: "train"
  test_dir: "test"
